### ISSUE TITLE
Tagname conflicts when using alongside carousel lib

### ISSUE THREAD

**Issue by maranmaran** [ivylaboratory/angular-gallery#3]
`Multiple components match node with tagname carousel`

Why not just include your carousel as a dependency in this project or rename this one?

If I just remove responsive carousel dependency as this one has it I get a bunch of build errors from missing config values and whatnot.

Am I missing something?

**Comment by EugeneHerasymchuk** [comment]
Not sure what did you mean about "removing responsive carousel dependency as this one". 
That's true, using gallery and carousel is not possible because they both have Carousel component, but they do not depend on each other.
It's just about naming convention of internal components

angular-responsive-carousel has its own:  https://github.com/ivylaboratory/angular-carousel/blob/master/src/app/carousel/carousel.component.ts

and angular-gallery as well: https://github.com/ivylaboratory/angular-gallery/blob/master/src/app/gallery/carousel.component.ts

**Comment by EugeneHerasymchuk** [comment]
Added a PR that potentially could help: https://github.com/ivylaboratory/angular-gallery/pull/4
